name: "Label Maker"
author: "Taj"
description: "Add labels for issues and pull requests based on its title"
branding:
    icon: "check"
    color: "black"
inputs:
    token:
        description: "Github token"
        required: true
runs:
    using: "docker"
    image: "Dockerfile"
