name: "Label Maker"
description: "Makes labels for new issues"
icon: "check"
color: "black"
inputs:
    token:
        description: "Github token"
        required: true
runs:
    using: "docker"
    image: "Dockerfile"