name: "Label Maker"
description: "Makes labels for new issues"
runs:
    using: "docker"
    image: "Dockerfile"
    inputs:
        TOKEN:
            description: "Github token"
            required: true
