on:
  issues:
    types: [opened]

jobs:
  label_maker:
    runs-on: ubuntu-latest
    name: Label Maker
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: Label Maker action step
        uses: ./
        id: labelmaker
