on:
  issues:
    types: [opened]

jobs:
  label_maker:
    runs-on: ubuntu-latest
    name: Label Maker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Label Maker action step
        uses: ./
        id: label-maker
        env:
          TOKEN: ${{ secrets.curl }}
